version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: permitai
      POSTGRES_USER: permitai
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-permitai123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-permitai}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-permitai123}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  ocr-service:
    build: ./infrastructure/ocr-service
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./infrastructure/ocr-service:/app
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  ollama_data:
  minio_data: